#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding		45
bspc config bottom_padding	5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#18a373'

bspc rule -a yakuake state=floating
bspc rule -a '*:zathura' state=tiled
