#! /bin/sh

# launch some nice programs
sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg & # set wallpaper

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          37
bspc config left_padding         10
bspc config right_padding        10
bspc config bottom_padding       10

bspc config focused_border_color '#18a373'

# startup layout
bspc rule -a firefox:Navigator -o node=@^1:^1:/
bspc rule -a Alacritty:Alacritty -o node=@^1:^2:/
bspc rule -a Alacritty:Alacritty -o node=@^1:^3:/
bspc rule -a TelegramDesktop:telegram-desktop -o node=@^1:^4:/
bspc rule -a KeePassXC:keepassxc -o node=@^1:^5:/
nm-applet &
firefox &
alacritty &
alacritty &
telegram-desktop &
keepassxc &

# rules
bspc rule -a yakuake state=floating
bspc rule -a '*:zathura' state=tiled
bspc rule -a plasmashell state=floating
