general.import = ["/home/bkorecic/.config/alacritty/themes/active.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Oblique"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"
